test_that("all geometry metrics are dual to the ambient differential", {
  skip_if_not(torch::torch_is_installed())
  torch::torch_manual_seed(310)
  for(label in names(geom_cases())) {
    M<-geom_cases()[[label]];x<-riem.random(M)
    expect_true(all(riem.belongs(M,x)),info=label)
    ambient<-torch::torch_randn_like(x);u<-riem.tangent(M,x,torch::torch_randn_like(x))
    u<-u/(1+scalar(riem.norm(M,x,u)))
    g<-riem.egrad2rgrad(M,x,ambient)
    expect_true(all(riem.istangent(M,x,g)),info=label)
    expect_equal(scalar(riem.inner(M,x,g,u)),scalar((ambient*u)$sum()),tolerance=2e-7,info=label)
    expect_gt(scalar(riem.inner(M,x,u,u)),0,label=label)
    expect_lt(normf(riem.retr(M,x,torch::torch_zeros_like(x))-x),1e-7,label=label)
    for(h in c(1e-3,1e-4,1e-5)) {
      d<-(riem.retr(M,x,u,h)-riem.retr(M,x,u,-h))/(2*h)
      expect_lt(normf(d-u),1e-4,label=paste(label,h))
    }
    y<-riem.retr(M,x,u,.01);v<-riem.transport(M,x,u,y,u,.01)
    expect_true(all(riem.belongs(M,y)),info=label)
    expect_true(all(riem.istangent(M,y,v)),info=label)
    if(isTRUE(M$capabilities$isometric_transport)) expect_equal(scalar(riem.inner(M,x,u,u)),scalar(riem.inner(M,y,v,v)),tolerance=1e-6,info=label)
  }
})
test_that("quotient gradients and steps respect independent gauges", {
  skip_if_not(torch::torch_is_installed());torch::torch_manual_seed(22)
  for(M in list(manifold.grassmann(5,2),manifold.spdk(5,2,"wasserstein","factor"),manifold.landmark(5,2))) {
    x<-riem.random(M);Q<-riem.random(manifold.rotation(2));target<-riem.random(M)
    f<-geom_loss(M,target);P<-riem.problem(M,f)
    a<-riem.evaluate(P,x);b<-riem.evaluate(P,x$matmul(Q))
    expect_equal(scalar(a$value),scalar(b$value),tolerance=1e-8)
    expect_lt(normf(b$gradient-a$gradient$matmul(Q)),1e-7)
    y<-riem.retr(M,x,a$gradient,-.01)
    z<-riem.retr(M,x$matmul(Q),b$gradient,-.01)
    expect_lt(normf(z-y$matmul(Q)),1e-7)
  }
})
test_that("matrix and factor Wasserstein representations are isometric", {
  skip_if_not(torch::torch_is_installed());torch::torch_manual_seed(9)
  F<-manifold.spdk(4,2,"wasserstein","factor");M<-manifold.spdk(4,2,"wasserstein")
  y<-riem.random(F);u<-riem.tangent(F,y,torch::torch_randn_like(y));v<-riem.tangent(F,y,torch::torch_randn_like(y))
  x<-y$matmul(y$t());push<-function(z) z$matmul(y$t())+y$matmul(z$t())
  expect_equal(scalar(riem.inner(F,y,u,v)),scalar(riem.inner(M,x,push(u),push(v))),tolerance=1e-7)
})
test_that("weighted products have reciprocal weight gradient conversion", {
  skip_if_not(torch::torch_is_installed())
  M<-manifold.product(list(a=manifold.euclidean(2),b=manifold.sphere(3)),c(2,5))
  x<-list(a=tensor(c(1,2)),b=tensor(c(1,0,0)))
  P<-riem.problem(M,function(z) (z$a^2)$sum()/2-z$b[2])
  ev<-riem.evaluate(P,x)
  expect_equal(as.numeric(ev$gradient$a),c(.5,1))
  expect_equal(as.numeric(ev$gradient$b),c(0,-.2,0))
  fit<-riem.optimize(P,x,"conjugate_gradient",list(max_iterations=150))
  expect_lt(fit$objective,-1+1e-7);expect_true(all(riem.belongs(M,fit$point)))
  expect_error(riem.belongs(M,list(b=x$b,a=x$a)),"named factors")
})
test_that("batch axes and noncontiguous inputs preserve dtype and gradients", {
  skip_if_not(torch::torch_is_installed())
  M<-manifold.sphere(3);x<-riem.random(M,batch_shape=c(2,4))
  expect_equal(x$shape,c(2,4,3));expect_true(all(riem.belongs(M,x)))
  u<-riem.tangent(M,x,torch::torch_randn_like(x));expect_equal(riem.inner(M,x,u,u)$shape,c(2,4))
  y<-riem.retr(M,x,u,.01);expect_true(all(riem.belongs(M,y)))
  expect_error(riem.tangent(M,x,x[1,,]),"shapes must match")
  expect_error(riem.optimize(riem.problem(M,function(x)x$sum()),x),"without batch")
  A<-riem.random(manifold.spd(3,"lerm"),batch_shape=2)$transpose(2,3)$requires_grad_(TRUE)
  expect_false(A$is_contiguous());z<-riem.matrix.function(A,"log");z$sum()$backward()
  expect_true(all(is.finite(as.numeric(A$grad))));expect_true(z$dtype==torch::torch_float64())
})
test_that("explicit domain boundaries are rejected", {
  skip_if_not(torch::torch_is_installed())
  expect_error(manifold.spd(3),"metric")
  expect_error(manifold.stiefel(3,2),"metric")
  expect_false(riem.belongs(manifold.multinomial(3),tensor(c(1,0,0))))
  expect_error(riem.retr(manifold.hyperbolic(2),tensor(c(0,0)),tensor(c(2,0))),"leaves")
  expect_error(riem.log(manifold.sphere(2),tensor(c(1,0)),tensor(c(-1,0))),"antipodes")
  M<-manifold.stiefel(3,2,"euclidean");x<-riem.random(M)
  expect_equal(as.numeric(riem.exp(M,x,torch::torch_zeros_like(x))),as.numeric(x))
})
test_that("nested products and rigid motions retain explicit factor structure", {
  skip_if_not(torch::torch_is_installed());torch::torch_manual_seed(49)
  M<-manifold.rigidmotion(3);target<-riem.random(M);initial<-riem.random(M)
  P<-riem.problem(M,function(x) ((x$rotation-target$rotation)^2)$sum()/2+((x$translation-target$translation)^2)$sum()/2)
  f0<-scalar(riem.evaluate(P,initial,FALSE)$value)
  fit<-riem.optimize(P,initial,control=list(max_iterations=100))
  expect_lt(fit$objective,f0);expect_true(riem.belongs(M,fit$point))
  nested<-manifold.product(list(motion=M,scale=manifold.euclidean(1)),c(2,3))
  x<-list(motion=initial,scale=tensor(2));u<-list(motion=riemtorch:::.zeros(initial),scale=tensor(1))
  expect_equal(scalar(riem.inner(nested,x,u,u)),3)
  expect_true(riem.belongs(nested,riem.retr(nested,x,u,.1)))
})
test_that("Grassmann projector and frame metrics agree under pushforward", {
  skip_if_not(torch::torch_is_installed());torch::torch_manual_seed(84)
  F<-manifold.grassmann(4,2);M<-manifold.grassmann(4,2,"projection")
  x<-riem.random(F);u<-riem.tangent(F,x,torch::torch_randn_like(x));v<-riem.tangent(F,x,torch::torch_randn_like(x))
  P<-x$matmul(x$t());push<-function(z) z$matmul(x$t())+x$matmul(z$t())
  expect_equal(scalar(riem.inner(F,x,u,v)),scalar(riem.inner(M,P,push(u),push(v))),tolerance=1e-9)
})
test_that("reflection quotient is an explicit Riemann shape variant", {
  skip_if_not(torch::torch_is_installed());torch::torch_manual_seed(79)
  M<-manifold.landmark(5,2,reflections=TRUE);x<-riem.random(M)
  Q<-torch::torch_diag(tensor(c(1,-1)));target<-riem.random(M);P<-riem.problem(M,geom_loss(M,target))
  a<-riem.evaluate(P,x);b<-riem.evaluate(P,x$matmul(Q))
  expect_equal(scalar(a$value),scalar(b$value),tolerance=1e-10)
  expect_lt(normf(b$gradient-a$gradient$matmul(Q)),1e-8)
  fit<-riem.optimize(P,x,control=list(max_iterations=40))
  expect_lt(fit$objective,scalar(a$value));expect_true(riem.belongs(M,fit$point))
})
